name: Daily Email Digest

on:
  schedule:
    # Runs at 5:30 AM UTC daily (11:00 AM IST)
    - cron: '30 5 * * *'
  
  # Allows manual triggering from Actions tab
  workflow_dispatch:

jobs:
  send-digest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if secret is set
        run: |
          if [ -z "${{ secrets.CRON_SECRET }}" ]; then
            echo "❌ CRON_SECRET is not set or is empty."
            exit 1
          else
            echo "✅ CRON_SECRET is loaded. ${{secrets.CRON_SECRET}}"
          fi
    
      - name: Debug Secret Characters (REMOVE AFTER DEBUG)
        run: |
            secret="${{ secrets.CRON_SECRET }}"
            for (( i=0; i<${#secret}; i++ )); do
              echo "Char $i: ${secret:$i:1}"
            done

      - name: Send Daily Email Digest
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          response=$(curl -s -L -w "\n%{http_code}" -X GET \
            -H "Authorization: Bearer $CRON_SECRET" \
            -H "Content-Type: application/json" \
            "https://safeornot.space/api/email")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "Response body: $body"
          echo "HTTP Status: $http_code"
          
          if [ "$http_code" -ne 200 ]; then
            echo "❌ Failed to send email digest (HTTP $http_code)"
            exit 1
          else
            echo "✅ Email digest sent successfully"
          fi

